# subset of Makefile used to generate headers on demand

OBJS := $(patsubst %.c, build/%.o, $(wildcard *.c))

-include $(OBJS:.o=.d)

gen/%.h: %.c makeheaders/makeheaders
	@mkdir -p gen
	./makeheaders/makeheaders $*.c:gen/$*.h
	touch gen/$*.h

linenoise/linenoise.h:
	git submodule init
	git submodule update

makeheaders/makeheaders: makeheaders/makeheaders.c
	$(CC) -O -w makeheaders/makeheaders.c -o makeheaders/makeheaders