@ simple operator => [ 3 ]
: 1 2 +

@ alts => [ { 10 | 15 | 14 | 21 } ]
: 2 3 | 5 7 | *

@ pushl/popr  => [ [] 3 ]
: 1 [2+] pushl popr

@ sharing test => [ [ 4 ] [ 2 ] ]
: [1+] dup [3] swap . swap [1] swap .

@ sharing test
: [[3 +]] dup popr 1 swap pushl

@ dup alt
: 1 2 | dup

@ compose alt
: [3] [2*] [2-] | .

@ compose dup
: [1] [dup] .

@ pushl sharing
: [3+] dup 1 swap pushl
: [dup] dup pushl

: 1 [dup] dup . pushl popr

@: [dup pushl popr] dup pushl popr
@: [dup pushl popr swap drop] dup pushl popr swap drop

: [[2] [3]] [drop 0] [swap drop 1] | popr 1 == ! drop . popr
: [[2] [3] 1] [0 == ! drop swap drop] [1 == ! drop drop] | . popr
: [2] [3] 0 [] pushl pushl pushl [0 == ! drop swap drop] [1 == ! drop drop] | . popr
 